version = 1

[[annotations]]
path = ["airlock_open.ogg","airlock_close.ogg","airlock_deny.ogg","boltsup.ogg","boltsdown.ogg"]
SPDX-FileCopyrightText = "ParadiseSS13"
SPDX-License-Identifier = "CC-BY-SA-3.0"
SPDX-FileAttributionText = "https://github.com/ParadiseSS13/Paradise/tree/275677675bf34c94e9dd2e5e4e257e76a960db94/sound/machines"

